# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pub_date',
            field=models.DateTimeField(verbose_name='publish date'),
        ),
    ]
