# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20171015_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='thumbnail1',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
